### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by ghost** [Lcrypto/puncturing-optimization#1]
The file "main.m" refers to 'H_336_672_nonReg.mat' which is not here.
Also 'PLATFORM' function in "main.m" is missing.

**Comment by ghost** [comment]
It seems that "main.m" and its dependencies are just to run BER simulations.
There's no need to have it here so maybe it's simpler to just remove these files.
There's no description of "find_puncture_pattern" ...is it giving another puncture
pattern? what's the relation to the pattern from GroupAndSort2?

**Comment by Lcrypto** [comment]
As I write in readme  puncturing pattern is syndrom Base classic puncturing search method and Group and sort it fast and more efficient k step recovery method. Main just another example of use.

**Comment by ghost** [comment]
Got it. I ran a quick check on how good the puncture pattern returned by GroupAndSort2
The test case I used was one of the AR4JA protograph codes : https://public.ccsds.org/Pubs/131x1o2e2s.pdf
which gives the mother matrix and  puncture pattern. The pattern from the standard gave quite a 
bit better BER performance. I was hoping for better results...still nice of you to share.

**Comment by Lcrypto** [comment]
Thank you for you comments. Ar4ja puncturing pattern was already optimize for improve treshold by PEXIT or RCA under protograph. This protograph code designed to be punctured, it improve treshold compare to not puncture irregular. For compare better puncture more to use it not as MET Approach, but as  rate adaptation. Result become much more better.

**Comment by ghost** [comment]
I have to solve both problems with the same mother code : best BER performance and rate adaption.
A lot of what you've put here looks useful. I tried your simulated annealing lifting and that's giving good
results so far. Although it is limited to single edge protographs. I'm going through the other packages you shared too but some need minor changes to compile under linux. Let me know if you have recommendations on what packages would be the best to try.

**Comment by Lcrypto** [comment]
It support multiple egde just place instead 1 in protograph 2 3 ...  
It generate file which contain circulant shifts separated by &
for example:
simulatedAnnealingEMD.exe -file proto.txt -circulant 500 -upGirth 6 -emd 2 -seed 123 -numberOfMatrices 1 -girth 8
16 6
1 0 0 0 0 1 0 1 0 1 1 0 1 0 0 2
1 1 0 0 0 0 0 1 1 0 0 1 0 1 1 2
0 1 1 0 0 0 0 1 0 1 0 1 0 1 0 3
0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1

16	6	500
440	-1	-1	-1	-1	1	-1	258	-1	0	65	-1	237	-1	-1	6&215	
53	75	-1	-1	-1	-1	-1	95	0	-1	-1	443	-1	251	0	284&257	
-1	104	363	-1	-1	-1	-1	67	-1	466	-1	5	-1	174	-1	425&488&97	
-1	-1	265	249	-1	-1	363	-1	59	-1	392	-1	-1	324	119	222	
-1	-1	-1	260	64	-1	429	-1	-1	383	402	-1	421	-1	348	392&402	
-1	-1	-1	-1	429	480	86	-1	234	-1	-1	114	41	-1	-1	118&41

**Comment by Lcrypto** [comment]
Please feel free to ask any further question. I shall happy to support wide use of my toolchain.

**Comment by ghost** [comment]
Thanks for your offer. Glad to see it can support multiple edges.

I tried to duplicate your result above but it doesn't seem to work : (last two rows are all -1)
16	6	500
440	-1	-1	-1	-1	260	-1	0	-1	86	95	-1	234	-1	-1	402&443	
53	75	-1	-1	-1	-1	-1	250	363	-1	-1	130	-1	203	65	5&114	
-1	104	363	-1	-1	-1	-1	480	-1	258	-1	59	-1	466	-1	237&421&41	
-1	-1	265	249	-1	-1	64	-1	429	-1	67	-1	-1	383	392	251	
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1
I'm running the linux version (both native linux and mingwin), they both produce the
same error. They both also give this compile time warning :

irregularldpc.h: In function long long int getRand(long long int):
irregularldpc.h:72:27: warning: integer overflow in expression [-Woverflow]
         ll q = RAND_MAX + 1;
                           ^
irregularldpc.h:75:30: warning: integer overflow in expression [-Woverflow]
             q *= (RAND_MAX + 1);
                              ^
irregularldpc.h:76:33: warning: integer overflow in expression [-Woverflow]
             x = x * (RAND_MAX + 1) + rand();
                                 ^
In file included from main.cpp:30:0:
irregularldpc.h: In function int getGirth(const std::vector<std::vector<std::vector<int> > >&, const std::vector<std::vector<int> >&, long long int):
irregularldpc.h:153:24: warning: integer overflow in expression [-Woverflow]
     return (1 << 31) - 1;

I don't think the warning is important. I can make minor changes to the code to make it go away
and the other examples I tried match your results...

**Comment by ghost** [comment]
I just noticed that your proto.txt file has 4 rows but the first line is 16 6
and the output has 6 rows. Maybe the proto.txt file is missing two rows?

**Comment by ghost** [comment]
I went ahead and tried another proto.txt files :
5 3
0 0 1 0 2
1 1 0 1 3
1 2 0 2 1
This is the AR4JA protograph with the last column punctured. I will test the mother code
(no puncturing) which has rate 2/5. With circulant 128, your program gives :
5	3	128
-1	-1	65	-1	32&77	
56	3	-1	29	110&0&23	
109	48&107	-1	38&32	93
Do you have a way to read this into matlab?
"qc2sparse.m" from other packages doesn't seem to handle circulant weight>1

The AR4JA codes are first lifted up by 4 to eliminate parallel edges.
This gives this protograph :
20 12
0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 
0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 
0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 
0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 
1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 
0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 
0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 
0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 
1 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 
0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 
0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 
0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1
which I lift by 32 :
20	12	32
-1	-1	-1	-1	-1	-1	-1	-1	27	-1	-1	-1	-1	-1	-1	-1	0	-1	-1	1	
-1	-1	-1	-1	-1	-1	-1	-1	-1	14	-1	-1	-1	-1	-1	-1	14	28	-1	-1	
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	31	-1	-1	-1	-1	-1	-1	0	0	-1	
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	30	-1	-1	-1	-1	-1	-1	0	3	
24	-1	-1	-1	2	-1	-1	-1	-1	-1	-1	-1	12	-1	-1	-1	27	13	22	-1	
-1	3	-1	-1	-1	1	-1	-1	-1	-1	-1	-1	-1	0	-1	-1	-1	8	5	10	
-1	-1	0	-1	-1	-1	29	-1	-1	-1	-1	-1	-1	-1	10	-1	24	-1	1	0	
-1	-1	-1	1	-1	-1	-1	5	-1	-1	-1	-1	-1	-1	-1	0	5	1	-1	8	
13	-1	-1	-1	-1	-1	26	15	-1	-1	-1	-1	17	11	-1	-1	31	-1	-1	-1	
-1	16	-1	-1	0	-1	-1	22	-1	-1	-1	-1	-1	25	25	-1	-1	10	-1	-1	
-1	-1	1	-1	13	0	-1	-1	-1	-1	-1	-1	-1	-1	21	11	-1	-1	5	-1	
-1	-1	-1	6	-1	23	6	-1	-1	-1	-1	-1	8	-1	-1	30	-1	-1	-1	3
The girth of the first lift is 6 and the second is 8. So the first lift probably has worst performance
I'll verify once I know how to read the first output into matlab.

**Comment by ghost** [comment]
I was able to modify qc2sparse to handle larger circulant weights.
This can handle weight<=4...it can be modified to handle more.

function H = qc2sparse4(qcHFileName)
fid = fopen(qcHFileName, 'r');
n = fscanf(fid, '%d', [1 1]);
m = fscanf(fid, '%d', [1 1]);
z = fscanf(fid, '%d', [1 1]);
I = sparse(eye(z));
Z = sparse(zeros(z));
H = [];
for i = 1:m
    T=[];
    for j = 1:n
        TT=Z;
        shift = fscanf(fid, '%d',  [1 1]);if(shift>-1),       TT=TT+circshift(I,[0,shift]);end;
        shift = fscanf(fid, '&%d', [1 1]);if(length(shift)>0),TT=TT+circshift(I,[0,shift]);end;
        shift = fscanf(fid, '&%d', [1 1]);if(length(shift)>0),TT=TT+circshift(I,[0,shift]);end;
        shift = fscanf(fid, '&%d', [1 1]);if(length(shift)>0),TT=TT+circshift(I,[0,shift]);end;
        %duplicate above line for higher weights...or put a loop if you wish 
        T=horzcat(T,TT);
    end
 H=[H;T];
end
fclose(fid);
end

**Comment by Lcrypto** [comment]
Thank you for implementation of QC parser. I shall add it. Inside some of project have weight 2 and 3. We usually not use large that 3 circulant in protograph due balance cycles because it require use twice lifting to get some large EMD Girth 8. It require increase size of protograph,which increase complexity of barrel shifter (equvivalent decrease effective throughput).

**Comment by Lcrypto** [comment]
Yes, mistake in example 16 6 proto.Thank you. I shall check multi-edge again. I already agree some comit from git and probably not check multi edge fuctionality. I use my version for lifting.

**Comment by Lcrypto** [comment]
I compile project and check multi edge, it work. In example 16 6 I just left last two row when write protograph, currently example in readme fixed.

**Comment by ghost** [comment]
Everything seems to be working. I used your program on a multi-edge protograph (another AR4JA example). Yours produced a higher girth (6 vs 4) and slightly better BER performance than what's in the standard. I also prefer QC matrices of weight=1. Can any of your packages transform a QC matrix
with circulant Z and weight=3 to another matrix of same size but weight=1? Z can be changed if necessary. I saw your floor_scale_modular lifting package but I think that takes a large H and large Z and produce a smaller H with a smaller Z so the performance will not be as good. Another option is to take
a multi-edge protograph and expand it into a single edge one...is that something any of your packages can do?

**Comment by Lcrypto** [comment]
You can do it by simple  twice lifting script with two loops for EMD and Girth. After reach time limit take best graph (max Girth and EMD) sparse representation ( H in qc2sparse) as protograph and lift H again. I have script but it part of very huge platform which I shall publish with future article.

**Comment by ghost** [comment]
Thanks for your comments. I would be very interested in trying your platform when you release it.
I'll close this issue  for now and I'll watch for your future releases.
